title: 'zaxbux.reviews::lang.controllers.reviews.list_title'
modelClass: Zaxbux\Reviews\Models\Review
list: $/zaxbux/reviews/models/review/columns.yaml
recordUrl: 'zaxbux/reviews/reviews/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: '0'
showSetup: true
showCheckboxes: 1
defaultSort:
    column: created_at
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
